updated export to check for and create src directory

diff --git a/export b/export
--- a/export
+++ b/export
@@ -14,6 +14,17 @@ repo="config"
 # dest directory for files, relative to ${repo}
 dest="src"
 
+# make sure destination can be safely written to
+if ! [ -e "${dest}" ];
+then # it doesn't exist
+    mkdir "${dest}"
+elif ! [ -d "${dest}" ];
+then # it does exist, but it isnt a directory
+    echo "error: destination directory exists, but is not a directory"
+    echo "aborting"
+    exit 1
+fi
+
 # files to be exported
 if [ "$#" -eq "0" ] ;
 then
